-- Guftagu initial migration - generated from schema.prisma
-- This is a placeholder; real SQL generated by `prisma migrate dev`
-- Run `npx prisma migrate dev --name init` with DATABASE_URL set to generate full migration

-- For brevity, we document that migration creates all tables defined in schema.prisma with constraints and indexes
-- See schema.prisma for full model definitions

-- Example: create extension if needed
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- The full migration SQL will be auto-generated by Prisma, including:
-- Users, Devices, Sessions, OtpChallenges, Conversations, Memberships, Messages, DeletedMessages, Attachments, Reactions, Receipts, PinnedMessages, InviteLinks, Plans, PlanOptions, PlanRsvps, PlanVotes, TriviaQuestions, TriviaSessions, TriviaParticipants, TriviaAnswers, Calls, PushTokens, Blocks, Reports

-- To generate locally:
-- docker-compose up -d postgres
-- DATABASE_URL=postgresql://guftagu:guftagu@localhost:5432/guftagu npx prisma migrate dev --name init
